import type { OpenAPIObject } from '@nestjs/swagger';
import deepmerge from 'deepmerge';
import { JSONSchema } from 'zod/v4/core';
import { fixAllRefs, convertToOpenApi3Point0 } from './utils';
import {
  DEFS_KEY,
  EMPTY_TYPE_KEY,
  PARENT_ADDITIONAL_PROPERTIES_KEY,
  PARENT_HAS_REFS_KEY,
  PARENT_ID_KEY,
  PARENT_METADATA_KEY,
  SELF_REQUIRED_KEY,
  UNWRAP_ROOT_KEY,
  USES_THREE_POINT_ONE_SYNTAX_KEY,
} from './const';
import { isDeepStrictEqual } from 'node:util';
import { assert } from './assert';

type DtoSchema = Exclude<
  Exclude<OpenAPIObject['components'], undefined>['schemas'],
  undefined
>[string];
type OpenAPIParameter = Exclude<
  Exclude<
    Exclude<OpenAPIObject['paths'], undefined>['/'],
    undefined
  >['parameters'],
  undefined
>[number];
type OperationsObject = Exclude<
  Exclude<Exclude<OpenAPIObject['paths'], undefined>['/'], undefined>['get'],
  undefined
>;

/**
 * This function performs some post-processing on the OpenAPI document.  It
 * should only touch parts of the document that were generated from nestjs-zod
 * DTOs.
 *
 * Specifically, this function:
 * 1. Removes empty `type` fields
 * 2. Renames OpenAPI schemas that have an explicit `id` field to match that
 *    `id`, instead of using the DTO class name
 * 3. If the DTO's schema references another zod schema, it adds that zod
 *    schema's OpenAPI representation to `components.schemas`
 * 4. If a DTO is created directly with an array zod schema, it ensures the
 *    OpenAPI schema is generated properly
 * 5. Handles recursive zod schemas
 * 6. Handles `null` properly based on the OpenAPI version
 *
 * @param doc - The OpenAPI document that is generated by `SwaggerModule.createDocument`
 * @param options.version - The version of OpenAPI to use.  Defaults to `auto`,
 * which will use the version of the OpenAPI object passed in.  Note if the
 * version is `3.1` then it impacts how `null` is handled.  In `3.0`, `nullable:
 * true` is used, while in `3.1` `anyOf: [..., { type: 'null' }]` is used
 * instead
 * @returns A cleaned up OpenAPI document
 */
export function cleanupOpenApiDoc(
  doc: OpenAPIObject,
  { version: versionParam = 'auto' }: { version?: '3.1' | '3.0' | 'auto' } = {},
): OpenAPIObject {
  const schemas: Record<string, DtoSchema> = {};
  const renames: Record<string, string> = {};
  const version =
    versionParam === 'auto'
      ? doc.openapi.startsWith('3.1')
        ? '3.1'
        : '3.0'
      : versionParam;

  for (const [oldSchemaName, oldOpenapiSchema] of Object.entries(
    doc.components?.schemas || {},
  )) {
    const { newSchema, newSchemaName, additionalNewSchemas } = cleanupSchema({
      oldSchemaName,
      oldOpenapiSchema,
      version,
    });

    for (const [additionalSchemaName, additionalSchema] of Object.entries(
      additionalNewSchemas,
    )) {
      registerSchema(schemas, additionalSchemaName, additionalSchema);
    }

    if (oldSchemaName !== newSchemaName) {
      renames[oldSchemaName] = newSchemaName;
    }

    registerSchema(schemas, newSchemaName, newSchema);
  }

  const paths = deepmerge<typeof doc.paths>(doc.paths, {});
  for (const { get, patch, post, delete: del, put, head } of Object.values(
    paths,
  )) {
    for (const methodObject of Object.values({
      get,
      patch,
      post,
      del,
      put,
      head,
    })) {
      fixRefsInBodies({ methodObject, renames });

      for (let i = 0; i < (methodObject?.parameters || []).length; i++) {
        assert(methodObject?.parameters, 'parameters is required');

        let parameter = methodObject.parameters[i];
        parameter = fixParameter(parameter, version);

        if (SELF_REQUIRED_KEY in parameter) {
          // Setting `deepObject` style for query params improves the
          // "Try it" experience in SwaggerUI, such that objects are
          // sent using square brackets when the request is sent
          if (
            'schema' in parameter &&
            parameter.in === 'query' &&
            typeof parameter.style === 'undefined' &&
            parameter.schema &&
            'type' in parameter.schema &&
            parameter.schema.type === 'object'
          ) {
            parameter.style = 'deepObject';
          }

          if ('schema' in parameter) {
            // Add `required` back to the schema since nestjs seems to remove it?
            if (
              Array.isArray(parameter.required) &&
              parameter.schema &&
              'type' in parameter.schema &&
              parameter.schema.type === 'object' &&
              typeof parameter.schema.required === 'undefined'
            ) {
              parameter.schema.required = parameter.required;
            }
            parameter.required = Boolean(parameter[SELF_REQUIRED_KEY]);
          }

          delete parameter[SELF_REQUIRED_KEY];
        }

        // Add each $def as a schema
        if (DEFS_KEY in parameter) {
          const defs = parameter[DEFS_KEY] as Record<
            string,
            JSONSchema.BaseSchema
          >;
          delete parameter[DEFS_KEY];

          for (const [defSchemaId, defSchema] of Object.entries(defs)) {
            let fixedDef;
            try {
              fixedDef = fixAllRefs({ schema: defSchema });
            } catch (err) {
              if (
                err instanceof Error &&
                err.message.startsWith('[fixAllRefs]')
              ) {
                throw new Error(
                  `[cleanupOpenApiDoc] Recursive schemas are not supported for parameters`,
                  { cause: err },
                );
              }
              throw err;
            }

            if (version === '3.0') {
              fixedDef = convertToOpenApi3Point0(fixedDef);
            }

            registerSchema(
              schemas,
              defSchemaId,
              // @ts-expect-error FIXME
              fixedDef,
            );
          }
        }

        methodObject.parameters[i] = parameter;
      }
    }
  }

  return {
    ...doc,
    paths,
    components: {
      ...doc.components,
      schemas,
    },
  };
}

/**
 * Registers a schema in the schema registry.
 *
 * Mutates `schemaRegistry`
 */
function registerSchema(
  schemaRegistry: Record<string, DtoSchema>,
  schemaName: string,
  schema: DtoSchema,
) {
  if (
    schemaRegistry[schemaName] &&
    !isDeepStrictEqual(schemaRegistry[schemaName], schema)
  ) {
    throw new Error(
      `[cleanupOpenApiDoc] Found multiple schemas with name \`${schemaName}\`.  Please review your schemas to ensure that you are not using the same schema name for different schemas`,
    );
  }

  schemaRegistry[schemaName] = schema;
}

/**
 * In the process of cleaning up the OpenAPI document, we may rename schemas.
 *
 * This function fixes the `$ref` fields in the request body and responses to
 * point to the correct schema names.
 *
 * Mutates `methodObject`
 */
function fixRefsInBodies({
  methodObject,
  renames,
}: {
  methodObject: OperationsObject | undefined;
  renames: Record<string, string>;
}) {
  const content =
    (methodObject?.requestBody &&
      'content' in methodObject.requestBody &&
      methodObject.requestBody.content) ||
    {};
  for (const requestBodyObject of Object.values(content)) {
    if (requestBodyObject.schema && '$ref' in requestBodyObject.schema) {
      const oldSchemaName = getSchemaNameFromRef(requestBodyObject.schema.$ref);
      if (renames[oldSchemaName]) {
        const newSchemaName = renames[oldSchemaName];
        requestBodyObject.schema.$ref = requestBodyObject.schema.$ref.replace(
          `/${oldSchemaName}`,
          `/${newSchemaName}`,
        );
      }
    }
  }

  for (const statusCodeObject of Object.values(methodObject?.responses || {})) {
    const content =
      (statusCodeObject &&
        'content' in statusCodeObject &&
        statusCodeObject.content) ||
      {};
    for (const responseBodyObject of Object.values(content)) {
      if (responseBodyObject.schema && '$ref' in responseBodyObject.schema) {
        const oldSchemaName = getSchemaNameFromRef(
          responseBodyObject.schema.$ref,
        );
        if (renames[oldSchemaName]) {
          const newSchemaName = renames[oldSchemaName];
          responseBodyObject.schema.$ref =
            responseBodyObject.schema.$ref.replace(
              `/${oldSchemaName}`,
              `/${newSchemaName}`,
            );
        }
      }
    }
  }
}

/**
 * Cleans up a schema.
 */
function cleanupSchema({
  oldSchemaName,
  oldOpenapiSchema,
  version,
}: {
  oldSchemaName: string;
  oldOpenapiSchema: DtoSchema;
  version: '3.1' | '3.0';
}) {
  const additionalNewSchemas: Record<string, DtoSchema> = {};
  // Ignore non-object types, which are not added by us
  if (!('type' in oldOpenapiSchema) || oldOpenapiSchema.type !== 'object') {
    return {
      newSchema: oldOpenapiSchema,
      newSchemaName: oldSchemaName,
      additionalNewSchemas,
    };
  }

  let newSchemaName = oldSchemaName;
  let addedDefs = false;
  let hasRefs = false;
  let usesThreePointOneSyntax = false;
  const defRenames: Record<string, string> = {};

  // Clone so we can mutate
  let newOpenapiSchema = deepmerge<typeof oldOpenapiSchema>(
    {},
    oldOpenapiSchema,
  );

  for (const [propertyName, propertySchema] of Object.entries(
    newOpenapiSchema.properties || {},
  )) {
    if (SELF_REQUIRED_KEY in propertySchema) {
      // Remove optional object properties from the parent `required` array.
      // Some versions of @nestjs/swagger add them because `selfRequired`
      // is used instead of `required: false` to avoid conflicts with
      // nested required arrays.
      if (!propertySchema[SELF_REQUIRED_KEY] && Array.isArray(newOpenapiSchema.required)) {
        newOpenapiSchema.required = newOpenapiSchema.required.filter(
          (name: string) => name !== propertyName,
        );
        if (newOpenapiSchema.required.length === 0) {
          delete newOpenapiSchema.required;
        }
      }
      delete propertySchema[SELF_REQUIRED_KEY];
      delete propertySchema.selfRequired;
    }

    if (USES_THREE_POINT_ONE_SYNTAX_KEY in propertySchema) {
      usesThreePointOneSyntax = Boolean(
        propertySchema[USES_THREE_POINT_ONE_SYNTAX_KEY],
      );
      delete propertySchema[USES_THREE_POINT_ONE_SYNTAX_KEY];
    }

    if (PARENT_HAS_REFS_KEY in propertySchema) {
      hasRefs = Boolean(propertySchema[PARENT_HAS_REFS_KEY]);
      delete propertySchema[PARENT_HAS_REFS_KEY];
    }

    // Remove `type` if we added `type: ''`
    if (EMPTY_TYPE_KEY in propertySchema && propertySchema[EMPTY_TYPE_KEY]) {
      delete propertySchema[EMPTY_TYPE_KEY];
      if ('type' in propertySchema && propertySchema.type === '') {
        delete propertySchema.type;
      }
    }

    // Rename the schema if using `meta({ id: "NewName" })`
    if (
      PARENT_ID_KEY in propertySchema &&
      typeof propertySchema[PARENT_ID_KEY] === 'string'
    ) {
      Object.assign(newOpenapiSchema, { id: propertySchema[PARENT_ID_KEY] });
      newSchemaName = propertySchema[PARENT_ID_KEY];
      delete propertySchema[PARENT_ID_KEY];
    }

    if (
      PARENT_METADATA_KEY in propertySchema &&
      typeof propertySchema[PARENT_METADATA_KEY] === 'object'
    ) {
      Object.assign(newOpenapiSchema, propertySchema[PARENT_METADATA_KEY]);
      delete propertySchema[PARENT_METADATA_KEY];
    }

    if (
      PARENT_ADDITIONAL_PROPERTIES_KEY in propertySchema &&
      typeof propertySchema[PARENT_ADDITIONAL_PROPERTIES_KEY] === 'boolean'
    ) {
      newOpenapiSchema.additionalProperties =
        propertySchema[PARENT_ADDITIONAL_PROPERTIES_KEY];
      delete propertySchema[PARENT_ADDITIONAL_PROPERTIES_KEY];
    }

    // Add each $def as a schema
    if (DEFS_KEY in propertySchema) {
      const defs = propertySchema[DEFS_KEY] as Record<
        string,
        JSONSchema.BaseSchema
      >;
      delete propertySchema[DEFS_KEY];

      if (!addedDefs) {
        // If the def has no ID, then we need to prefix the def key
        // with the root schema name to make it globally unique
        // This can happen if the def is part of a recursive schema
        // (for example, `___schema0`)
        for (const [defSchemaId, defSchema] of Object.entries(defs)) {
          if (!('id' in defSchema)) {
            defRenames[defSchemaId] = `${newSchemaName}${defSchemaId}`;
          }
        }

        for (const [defSchemaId, defSchema] of Object.entries(defs)) {
          let fixedDef = fixAllRefs({
            schema: defSchema,
            rootSchemaName: newSchemaName,
            defRenames,
          });

          if (version === '3.0') {
            fixedDef = convertToOpenApi3Point0(fixedDef);
          }

          const newDefSchemaKey = defRenames[defSchemaId] || defSchemaId;

          registerSchema(
            additionalNewSchemas,
            newDefSchemaKey,
            // @ts-expect-error FIXME
            fixedDef,
          );
        }

        addedDefs = true;
      }
    }
  }

  if (newSchemaName !== oldSchemaName && 'id' in newOpenapiSchema) {
    newOpenapiSchema['id'] = newSchemaName;
  }

  if (hasRefs) {
    // @ts-expect-error FIXME TODO: fix this
    newOpenapiSchema = fixAllRefs({
      // @ts-expect-error TODO: fix TS error
      schema: newOpenapiSchema,
      rootSchemaName: newSchemaName,
      defRenames,
    });
  }

  // Zod generates openapi schemas like this when a field is nullable:
  //
  // {
  //   anyOf: [
  //     { type: 'string' },
  //     { type: 'null' }
  //   ]
  // }
  //
  // However, this is not valid openapi in 3.0.  So if the user wants to generate openapi 3.0 docs,
  // we convert it to this:
  //
  // {
  //   type: 'string',
  //   nullable: true
  // }
  //
  // This is the default behavior, since nestjs/swagger seems to generate
  // a 3.0 document by default
  if (usesThreePointOneSyntax && version === '3.0') {
    // @ts-expect-error TODO: fix this
    newOpenapiSchema = convertToOpenApi3Point0(newOpenapiSchema);
  }

  // When the consumer does this `createZodDto(z.array(...))`, then
  // `_OPENAPI_METADATA_FACTORY` will return:
  // `{ root: { type: 'array', [UNWRAP_ROOT_KEY]: true } }`
  // This is a workaround for the fact that the factory doesn't support
  // returning array schemas directly.
  // If we see `UNWRAP_ROOT_KEY`, then we unwrap the array
  // schema (replace the root object schema with the array schema)
  if (
    newOpenapiSchema.properties &&
    'root' in newOpenapiSchema.properties &&
    UNWRAP_ROOT_KEY in newOpenapiSchema.properties.root
  ) {
    const replaceRoot = newOpenapiSchema.properties.root[UNWRAP_ROOT_KEY];
    delete newOpenapiSchema.properties.root[UNWRAP_ROOT_KEY];
    if (replaceRoot) {
      // @ts-expect-error TODO: fix this
      newOpenapiSchema = newOpenapiSchema.properties.root;
    }
  }

  if (
    additionalNewSchemas[newSchemaName] &&
    !isDeepStrictEqual(additionalNewSchemas[newSchemaName], newOpenapiSchema)
  ) {
    throw new Error(
      `[cleanupOpenApiDoc] Found multiple schemas with name \`${newSchemaName}\`.  Please review your schemas to ensure that you are not using the same schema name for different schemas`,
    );
  }

  return {
    newSchema: newOpenapiSchema,
    newSchemaName: newSchemaName,
    additionalNewSchemas,
  };
}

/**
 * Fixes various issues with parameters:
 * 1. Removes empty `type` fields
 * 2. Moves `const` from the root level of the parameter object to the schema
 * 3. Fixes refs to point to components.schemas
 * 4. Removes some nestjs-zod markers
 */
function fixParameter(
  parameterInput: OpenAPIParameter,
  version: '3.1' | '3.0',
) {
  const parameter = deepmerge<typeof parameterInput>({}, parameterInput);
  let usesThreePointOneSyntax = false;

  // nestjs seems to move some stuff out of the schema and into the root level of the parameter object 🤷
  if (EMPTY_TYPE_KEY in parameter) {
    delete parameter[EMPTY_TYPE_KEY];
    if (
      'schema' in parameter &&
      parameter.schema &&
      'type' in parameter.schema
    ) {
      delete parameter.schema.type;
    }
  }

  if (UNWRAP_ROOT_KEY in parameter) {
    throw new Error(
      `[cleanupOpenApiDoc] Query or url parameters must be an object type`,
    );
  }

  if ('const' in parameter && 'schema' in parameter && parameter.schema) {
    Object.assign(parameter.schema, { const: parameter.const });
    delete parameter.const;
  }

  if (PARENT_ID_KEY in parameter) {
    delete parameter[PARENT_ID_KEY];
  }

  if (PARENT_HAS_REFS_KEY in parameter) {
    delete parameter[PARENT_HAS_REFS_KEY];

    if ('schema' in parameter) {
      try {
        // @ts-expect-error TODO: fix this
        parameter.schema = fixAllRefs({ schema: parameter.schema });
      } catch (err) {
        if (err instanceof Error && err.message.startsWith('[fixAllRefs]')) {
          throw new Error(
            `[cleanupOpenApiDoc] Recursive schemas are not supported for parameters`,
            { cause: err },
          );
        }
        throw err;
      }
    }
  }

  if (USES_THREE_POINT_ONE_SYNTAX_KEY in parameter) {
    usesThreePointOneSyntax = Boolean(
      parameter[USES_THREE_POINT_ONE_SYNTAX_KEY],
    );
    delete parameter[USES_THREE_POINT_ONE_SYNTAX_KEY];
  }

  if (PARENT_ADDITIONAL_PROPERTIES_KEY in parameter) {
    delete parameter[PARENT_ADDITIONAL_PROPERTIES_KEY];
  }

  if (
    version === '3.0' &&
    'schema' in parameter &&
    parameter.schema &&
    usesThreePointOneSyntax
  ) {
    // @ts-expect-error TODO: fix this
    parameter.schema = convertToOpenApi3Point0(parameter.schema);
  }

  return parameter;
}

function getSchemaNameFromRef(ref: string) {
  const lastSlash = ref.lastIndexOf('/');
  const schemaName = ref.slice(lastSlash + 1);
  return schemaName;
}
